#
# Copyright The Titan Project Contributors.
#

#
# When a tag is pushed, build and upload the binary to the in-progress draft release.
#
name: Release

on: create

jobs:
  upload:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - uses: toolmantim/release-drafter@v5.5.0
        id: draft_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo
        run: echo $UPLOAD_URL
        env:
          UPLOAD_URL: ${{ steps.draft_release.outputs.upload_url }}
      - name: Build
        run: go build ./cmd/docker-volume-proxy
      - name: Test
        run: go test ./...
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ./docker-volume-proxy
          asset_name: docker-volume-proxy
          asset_content_type: application/octet-stream
